export const buisnesses = {
    shop : {
        name : 'Магазин',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1500,
        startIncome : 3,
        startPrice : 1000,
        infoAbout : ' Магазин является пассивным бизнесом. Улучшения повышают доходв час.',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: './images/shop.png',
    },
    barber : {
        name : 'Барбершоп',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 5,
        startPrice : 2000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },
    workshop : {
        name : 'Цех',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 7,
        startPrice : 3000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },
    pool : {
        name : 'Бассейн',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 10,
        startPrice : 4000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },
    auto : {
        name : 'Автодиллер',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 13,
        startPrice : 5000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },
    delivery : {
        name : 'Грузоперевозки',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 17,
        startPrice : 7000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },
    clinic : {
        name : 'Клиника',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 22,
        startPrice : 9000,
        infoAbout : '',
        lastUpgradePrice : 1500,
    },
    hotel : {
        name : 'Отель',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 12,
        startPrice : 5000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },
    bank : {
        name : 'Банк',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        startUpgradePrice: 1,
        startIncome : 33,
        startPrice : 15000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        imageLink: '',
    },

}