export const buisnesses = {
    shop : {
        name : 'Магазин',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 6,
        income : 3,
        startPrice : 1000,
        infoAbout : ' Магазин является пассивным бизнесом. Улучшения повышают доход в час.',
        lastUpgradePrice : 5,
        currentIncome : 3,
        made: false,
    },
    barber : {
        name : 'Барбершоп',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 5,
        startPrice : 2000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    workshop : {
        name : 'Цех',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 7,
        startPrice : 3000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    pool : {
        name : 'Бассейн',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 10,
        startPrice : 4000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    auto : {
        name : 'Автодиллер',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 13,
        startPrice : 5000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    delivery : {
        name : 'Грузоперевозки',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 17,
        startPrice : 7000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    clinic : {
        name : 'Клиника',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 22,
        startPrice : 9000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    hotel : {
        name : 'Отель',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 12,
        startPrice : 5000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },
    bank : {
        name : 'Банк',
        active : false,
        type : false,
        lvl : 0,
        scalePrice : 1.8,
        scaleIncome : 1.3,
        upgradeTime : 4,
        timeScale: 1.4,
        upgradePrice: 1,
        income : 33,
        startPrice : 15000,
        infoAbout : '',
        lastUpgradePrice : 1500,
        currentIncome : 3,
        made: false,
    },

}